FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY client/package*.json ./
RUN npm install

# Bundle app source
COPY client/ .
RUN npm run build

# Install http-server to serve the static files
RUN npm install -g http-server

EXPOSE 8080
CMD [ "http-server", "dist" ]